### PR TITLE
Dockerize the script for telegraf

### PR DESCRIPTION
**Pull request by chevdor**
Hello, first of all, many thanks for your work and sharing it.

You will find a few things in this PR, everything mostly targeting Docker in order to make things much easier.
I would have preferred a few smaller PRs but the changes kind had to come together.

- First of all I moved the variables that were hardcoded to ENV variable with defaults similar to what you had
- I introduced 2 .*ignore files to keep the source tidy
- The `Dockerfile` is obviously to create the docker image and you will find the steps of your readme in there
- I moved a few files around to keep the repo tidy and make it easier to ignore some files (such as the doc) and keep the docker image small
- I created a `requirements.txt` file so you can skip some explanations in the doc
- I added some doc
- I added a full telegraf config that can be used as base in the image (`telegraf-docker-sample.conf `)
 
The impact on the installation procedure is the following:

> Several prerequisites need to be met to successfully install this script and generate the metrics. Some seem to be obvious but will be mentioned here for sake of complete documentation.

This gets much smaller :)

> Have an operational TIG stack (Telegraf, InfluxDB Grafana) with all of them installed and operational.

That is still required. No change here.

> Activate the TR-064 protocoll in the Fritzbox (Heimnetz -> Netzwerk -> Netzwerkeinstellungen)
> Have a dedicated user on the Fritz!Box (the username:Telegraf is assumed, but any will do)

No change

> Install python3 and pip (for example: apt install python3-pip)
> Locally clone the fritzconnection library (pip3 install fritzconnection)
> Clone this project (git clone https://github.com/Schmidsfeld/TelegrafFritzBox/)
> Edit the python file and adjust the credentials (nano ./TelegrafFritzBox/telegrafFritzBox.py)
> Make it executeamle (chmod +x ./TelegrafFritzBox/telegrafFritzBox.py)
> Test the output (python3 ./TelegrafFritzBox/telegrafFritzBox.py)
> Copy it to the appropiate locatio (cp ./TelegrafFritzBox/telegrafFritzBox.py /usr/local/bin)
> Copy the Telegraf config file to the correct location or append it to your current file (cp ./TelegrafFritzBox/telegrafFritzBox.conf /etc/telegraf/telegraf.d)
>Restart your Telegraf service (systemctl restart telegraf)

This whole big chunk is no longer required as it is part of the docker image.
Instead, users can build their own image or pull one and run:

```
docker run --rm -it --env-file .env -v $PWD/telegraf.conf:/etc/telegraf/telegraf.conf:ro chevdor/fritzgraf
```
> Load your Grafana dashboard (GrafanaFritzBoxDashboard.json)

No change

### CODE REVIEW

**Review by Schmidsfeld — COMMENTED** [review]
Thank you for the PR

Will do some small changes to the main file to keep it consistent.

**Comment by chevdor** [comment]
FYI @Schmidsfeld I tipped you some BAT. If you enable that for Github, you should get them :)

**Comment by Schmidsfeld** [comment]
Thank you for the kind tip.
I haven't seen them on github yet, but am aware of the concept from the brave browser. I will figure it out after merging the code fully..

**Comment by chevdor** [comment]
If you use Brave, some extra tipping icons show up in GitHub.

**Pull request merged**
