### PR TITLE
Fix for cable modems

### PR DESCRIPTION
**Pull request by chevdor**
This PR properly gets the connectionInfo for cable modems

### CODE REVIEW

**Review by Schmidsfeld — COMMENTED** [review]
This version won't run for me. I get a password error right away!  

Also the get connection Info breaks with the current style and thus greatly reduces readabillity. Can it be directly done in the main code preferabely by some variables we have available anyhow:
if connectionType == 'DSL':
    connectionInfo = XXXXXXXXXx
elif connectionType == 'Cable':
    ........


In conclusion I will have to do a in depth trace before merging this version

**Comment by chevdor** [comment]
Before that I remove the `superstrongpassword` default that we def. don't want.
I also fixed the NAME of the ENV which is likely causing your troubles.

image

I suggest we get a working version together and you fix the style as you wish. For now, I started packing thing into functions will make it later more testable.

I am rather new to the TR-064 specs but it sounds like we may be able to avoid the issue entirely using the something like `WANCommonInterfaceConfig1`. That should give us metrics common to DSL and cable.

**Comment by Schmidsfeld** [comment]
Ah yes The password and the missing default (before that the missing comma before the default was my connection problem. - I have a script to replace "SuperStrongPassword" with my actual password when pushing it onto the Pi when deploying ...

I think you found and solved the problem for the root cause 👍 
I will get a working version based on `WANCommonInterfaceConfig1` going. 
Also the detection of the connection type and appropiate **'Special'** stats should be no problem.

Hope to be able to provide a new version later today / tommorrow.

With your help testing it and detecting some output we soon should have a universal version.

Thank you for contributing so much to this project!

**Review by Schmidsfeld — APPROVED** [review]

**Comment by Schmidsfeld** [comment]
Sorry bit this build makes the code horrible broken for DSL Line! Cant merge at the moment!

**Comment by chevdor** [comment]
No problem, I am blind on the DSL side...
What is the issue ?

There are only a few places to check:
- is the `isDSL` function working fine ?
- is the code inside the DSL only block working fine ?

**Comment by chevdor** [comment]
I checked the PR again and if there is an issue, it must be in `isDSL`. The rest did not change in functionality.

**Comment by Schmidsfeld** [comment]
Sorry this is horrible broken for DSL Lines. All the specialized stats (FEC Errors are missing!
I cant merge it in this form.

I will get a workarround for cable done myself. Seems less work than chasing down the errors and adjusting the code to be constistent with the prevalent style...

**Pull request closed without merging**
